let suggestions = [
    "Canal",
    "YouTube",
    "YouTuber",
    "Carros",
    "Facebook",
    "Instagram",
    "Projetos CSS",
    "telegram",
    "TWD",
    "The Walking Dead",
    "Negan",
    "Rick Grimes",
    "Darly Dixon",
    "Lance",
    "PS1",
    "PS2",
    "PS3",
    "PS4",
    "PS5",
    "xbox one",
    "xbox serie x",
    "xbox serie s",
    "xbox 360",
    "God of war",
    "XV de Piracicba",
    "Telegram",
    "Robocop",
    "Velozes e furiosos 10 download grátis",
    "Velozes e furiosos 1",
    "Velozes e furiosos 2",
    "Velozes e furiosos 3",
    "Velozes e furiosos 4",
    "Velozes e furiosos 5",
    "Velozes e furiosos 6",
    "Velozes e furiosos 7",
    "Velozes e furiosos 8",
    "Velozes e furiosos 9",
    "Velozes e furiosos 10",
    "Windows XP",
    "Windows 10",
    "Windows 11",
    "Windows 7",
    "Windows 8",
    "Windows 8.1",
    "Windows 1.0",
    "Windows 2.0",
    "Windows 3.0",
    "Windows NT",
    "Windows 2.11",
    "Windows 95",
    "Windows 98",
    "Windows Me",
    "Windows 2000",
    "Windows Vista",
    "Minecraft",
    "Clash Royale",
    "Pica-Pau",
    "Freefire",
    "Youtube Kids",
    "Chaves",
    "Dead City",
    "Serie Rick e Michonne",
    "Desodorante",
    "H20",
    "Quimica",
    "Matematica",
    "Duolingo",
    "Todo mundo odeia o Chis",
    "Vida Cap",
    "Phonk",
    "Funk",
    "Gospel",
    "Sertanejo",
    "Pagode",
    "Samba",
    "Macaco",
    "leão",
    "Elefante",
    "Memes",
    "Ucrania",
    "Urano",
    "Oscar",
    "Onitorinco",
    "Água",
    "Agua",
    "Área 51",
    "Area 51",
    "Area",
    "Área",
    "Areia",
    "Jacó seguro o anjo",
    "Corinho",
    "Corinhos",
    "Corinhos de fogo",
    "Filho",
    "Filha",
    "Xuxa",
    "Silvio Santos",
    "Kratos",
    "Bola",
    "Bolas",
    "Bicicleta",
    "Zebra",
    "Zebras",
    "Zoro",
    "Poortfolio",
    "Computador",
    "Nomes",
    "CPF",
    "Banco do Brasil",
    "Banco do Bradesco",
    "Bradesco",
    "Banco do Itaú",
    "Itaú",
    "Banco da Caixa",
    "Caixa",
    "Caixa Economica Federal",
    "Caixa Economica Fedral",
    "Amigos",
    "Colegas",
    "Escola",
    "Faculdade",
    "Ceverja",
    "Cervejas",
    "Maconha",
    "Drogras",
    "Drogra",
    "Cadeiras",
    "Cadeira",
    "Pingos de chuvas",
    "Chuva",
    "Bolinho de chuva",
    "Teclado",
    "Mouse",
    "Vida",
    "Morte",
    "Amor",
    "Depressão",
    "Separação",
    "Igreja",
    "Companhia",
    "Pacote Office",
    "Pacote Office Craqueado",
    "Amizades",
    "Amizade",
    "Nike",
    "Addidas",
    "PlayBlack",
    "Karokê",
    "Presidente",
    "Presidente Prudente",
    "Placa",
    "Placa de carro",
    "PL",
    "PT",
    "Google",
    "Chorme",
    "Celular",
    "Samsung",
    "Iphone",
    "Iphone 1",
    "Iphone 2",
    "Iphone 3",
    "Iphone 4",
    "Iphone 5",
    "Iphone 6",
    "Iphone 7",
    "Iphone 8",
    "Iphone 9",
    "Iphone 10",
    "Iphone 10 Pro",
    "Iphone 10 Pro Max",
    "Iphone 11 Pro",
    "Iphone 11 Pro Max",
    "Iphone 12 Pro",
    "Iphone 12 Pro Max",
    "Iphone 13 Pro",
    "Iphone 13 Pro Max",
    "Iphone 14 Pro",
    "Iphone 14 Pro Max",
    "Iphone 15 Pro",
    "Iphone 15 Pro Max",
    "Iphone Mini",
    "Moto Moto",
    "Motorola",
    "Tijolão",
    "Gás",
    "Butijão de gás",
    "Pão de queijo",
    "Queijo",
    "Queijo de Minas",
    "Minas Gerais",
    "São Paulo",
    "Brasil",
    "Brazil",
    "Pen Drive",
    "Bugger King",
    "BK",
    "MacDonals",
    "MC",
    "Amazon",
    "Netflix",
    "Disney",
    "Disney Plus",
    "C++",
    "CSS",
    "Função",
    "Funções",
    "Etec",
    "Fatec",
    "Enem",
    "TV",
    "Alexandria",
    "Hiltop",
    "Lixo",
    "Hilter",
    "Adolf Hitler",
    "Putin",
    "Obama",
    "Barack Obama",
    "Trump",
    "Donald Trump",
    "Bolsonaro",
    "Jair Messias Bolsonaro",
    "Jair Bolsonaro",
    "Lula",
    "Luis Inacio Lula da Silva"
  ];